[server]
# Enhanced Edge browser compatibility settings
headless = false
port = 8502
enableCORS = false
enableXsrfProtection = false
allowRunOnSave = true
runOnSave = false
enableStaticServing = false
enableWebsocketCompression = false
maxUploadSize = 200
maxMessageSize = 200

[browser]
# Improve Edge compatibility
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8502

[client]
# Enhanced WebSocket settings for Edge support
toolbarMode = "viewer"
showErrorDetails = true
showSidebarNavigation = true

[logger]
# Reduce console noise
level = "warning"

[theme]
# Default theme settings
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
